python example/deploy/deploy_former.py \
    --base_model_name "MemoryMatters_VLA"\
    --base_model_class "none"\
    --base_model_path "none"\
    --base_task_name "rearrange_block_mem"\
    --base_robot_name "xspark_robot"\
    --base_robot_class "XsparkRobot"\
    --robotwin \
    --overrides \
    --execution_ckpt "/home/xspark-ai/project/control_your_robot/src/robot/policy/MemoryMatters_VLA/checkpoints/rearrange_block_real.pt" \
    --state_stats_path "/home/xspark-ai/project/control_your_robot/src/robot/policy/MemoryMatters_VLA/assets/rearrange_block_real/norm_stats.json" \
    --video "cam_head" \
    --action_horizon 20