python example/deploy/deploy_origin.py \
    --base_model_name "ACT"\
    --base_model_class "MYACT"\
    --base_model_path "/home/xspark-ai/project/control_your_robot/src/robot/policy/ACT/act_ckpt/act-rearrange_nohands/demo_clean/"\
    --base_task_name "rearrange_block_act"\
    --base_robot_name "xspark_robot"\
    --base_robot_class "XsparkRobot" \
    --robotwin \
    --overrides \
    --task_name "rearrange_nohands" \
    --task_config "demo_clean" \
    --ckpt_setting "" \
    --ckpt_dir "/home/xspark-ai/project/control_your_robot/src/robot/policy/ACT/act_ckpt/act-rearrange_nohands/demo_clean/" \
    --seed 0 \
    --temporal_agg true \
    --video "cam_head"