import sys
sys.path.append("./")

import numpy as np

from robot.robot.base_robot import Robot

from robot.controller.Y1_controller import Y1Controller
# from robot.sensor.Cv_sensor import CvSensor
from robot.sensor.V4l2_sensor import V4l2Sensor

from robot.utils.worker.worker_thread import Worker
from robot.utils.worker.time_scheduler_thread import TimeScheduler
from robot.data.collect_any import CollectAny

from robot.utils.base.data_handler import is_enter_pressed, debug_print
import time

from threading import Event
from threading import Lock

# setting your realsense serial
# Based on v4l2-ctl output, your cameras are at indices 0, 2, and 4.
# Please check the images generated by tools/check_camera_indices.py to assign correctly.
CAMERA_SERIALS = {
    'head': "/dev/video0",        # Candidate index
    'left_wrist': "/dev/video2",  # Candidate index
    'right_wrist': "/dev/video4", # Candidate index
}

# Define start position (in degrees)
START_POSITION_ANGLE_LEFT_ARM = [
    0,   # Joint 1
    0,    # Joint 2
    0,  # Joint 3
    0,   # Joint 4
    0,  # Joint 5
    0,    # Joint 6
]

# Define start position (in degrees)
START_POSITION_ANGLE_RIGHT_ARM = [
    0,   # Joint 1
    0,    # Joint 2
    0,  # Joint 3
    0,   # Joint 4
    0,  # Joint 5
    0,    # Joint 6
]

condition = {
    "save_path": "./save/",
    "task_name": "test",
    "save_format": "hdf5",
    "save_freq": 10, 
}

class DataBuffer:
    def __init__(self):
        self.data_buffer = {}
        self.show_buffer = {}
        self.raw_lock = Lock()
        self.show_lock = Lock()
    
    def push(self, name, data):
        with self.raw_lock:
            self.data_buffer[name] = data
    
    def update(self, name, data):
        with self.show_lock:
            self.show_buffer[name] = data

    def get(self):
        with self.raw_lock:
            return self.data_buffer.copy()
    
    def show(self):
        with self.show_lock:
            return self.show_buffer.copy()

class component_worker(Worker):
    def __init__(self, process_name: str, start_event, end_event, component, data_buffer:DataBuffer):
        super().__init__(process_name, start_event, end_event)
        self.component = component
        self.data_buffer = data_buffer
    
    def component_init(self):
        return
    
    def handler(self):
        data = self.component.get() 
        self.data_buffer.push(self.process_name, data)

class data_worker(Worker):
    def __init__(self, process_name: str, start_event, end_event, data_buffer:DataBuffer):
        super().__init__(process_name, start_event, end_event)
        self.data_buffer = data_buffer

    def component_init(self):
        return

    def handler(self):
        data = self.data_buffer.get() 
        # print(data.keys())
        
        for key in data.keys():
            self.data_buffer.update(key, data[key])

class XsparkRobot(Robot):
    def __init__(self, condition=condition, move_check=False, start_episode=0):
        super().__init__(condition=condition, move_check=move_check, start_episode=start_episode)
        self.first_start = True
        self.controllers = {
            "arm":{
                "left_arm": Y1Controller("left_arm"),
                "right_arm": Y1Controller("right_arm"),
            },
        }
        self.sensors = {
            "image": {
                "cam_head": V4l2Sensor("cam_head"),
                "cam_left_wrist": V4l2Sensor("cam_left_wrist"),
                "cam_right_wrist": V4l2Sensor("cam_right_wrist"),
            },
        }
    
    def get(self):
        data = self.data_buffer.show()

        controller_data = {
            "left_arm": data["left_arm"],
            "right_arm": data["right_arm"],
        }

        sensor_data = {
            "cam_head": data["cam_head"],
            "cam_left_wrist": data["cam_left_wrist"],
            "cam_right_wrist": data["cam_right_wrist"],
        }
        return controller_data, sensor_data
    
    def set_up(self, teleop=False):
        super().set_up()
        
        self.controllers["arm"]["left_arm"].set_up("can1", teleop=teleop)
        self.controllers["arm"]["right_arm"].set_up("can0", teleop=teleop)

        self.sensors["image"]["cam_head"].set_up(CAMERA_SERIALS['head'],is_depth=False, is_jepg=True)
        self.sensors["image"]["cam_left_wrist"].set_up(CAMERA_SERIALS['left_wrist'], is_depth=False, is_jepg=True)
        self.sensors["image"]["cam_right_wrist"].set_up(CAMERA_SERIALS['right_wrist'],is_depth=False, is_jepg=True)
        
        self.set_collect_type({"arm": ["joint","qpos","gripper"],
                                "image": ["color"]
                               })
        print("set up success!")

        self.data_buffer = DataBuffer()
        self.start_event, self.end_event = None, Event() 
        
        self.controller_workers = []
        for controller_type, type_name in self.controllers.items():
            for controller_name, controller in type_name.items():
                controller_worker = component_worker(controller_name, self.start_event, self.end_event, \
                                    self.controllers[controller_type][controller_name], self.data_buffer)
                self.controller_workers.append(controller_worker)
        
        self.sensor_workers = []
        for sensor_type, type_name in self.sensors.items():
            for sensor_name, sensor in type_name.items():
                sensor_worker = component_worker(sensor_name, self.start_event, self.end_event, \
                                self.sensors[sensor_type][sensor_name], self.data_buffer)
                
                self.sensor_workers.append(sensor_worker)
        
        update_worker = data_worker("data_worker", self.start_event, self.end_event, self.data_buffer)
        self.controller_scheduler = TimeScheduler(process_name="time_scheduler_controller", work_events=[controller_worker.forward_event for controller_worker in self.controller_workers],\
                                            time_freq=120)

        self.sensor_scheduler = TimeScheduler(process_name="time_scheduler_sensor", work_events=[sensor_worker.forward_event for sensor_worker in self.sensor_workers],\
                                            time_freq=60)

        self.update_scheduler = TimeScheduler(process_name="time_scheduler_sensor", work_events=[update_worker.forward_event],\
                                            time_freq=120)
        
        for controller_worker in self.controller_workers:
            controller_worker.start()
        for sensor_worker in self.sensor_workers:
            sensor_worker.start()
        
        update_worker.start()

        # 等待, 避免第一帧没刷新
        time.sleep(1)
        self.controller_scheduler.start()
        self.sensor_scheduler.start()
        self.update_scheduler.start()

    def reload_cameras(self):
        try:
            """Cleanup existing camera devices"""
            self.sensors["image"]["cam_head"].cleanup()
            self.sensors["image"]["cam_left_wrist"].cleanup()
            self.sensors["image"]["cam_right_wrist"].cleanup()
            print("Cleaning up existing cameras done.")

            """Reload camera devices"""
            self.sensors["image"]["cam_head"].set_up(CAMERA_SERIALS['head'], is_depth=False)
            self.sensors["image"]["cam_left_wrist"].set_up(CAMERA_SERIALS['left_wrist'], is_depth=False)
            self.sensors["image"]["cam_right_wrist"].set_up(CAMERA_SERIALS['right_wrist'], is_depth=False)
            print("Cameras reloaded successfully.")
        except Exception as e:
            print(f"Error reloading cameras: {str(e)}")

    def reset(self):
        self.change_mode(teleop=False)
        move_data = {
            "arm":{
                "left_arm":{
                    "joint": [0, 0, 0, 0, 0, 0],
                    "gripper":  1.0,
                },
                
                "right_arm":{
                    "joint": [0, 0, 0, 0, 0, 0],
                    "gripper":  1.0,
                }
            }
        }
        self.move(move_data)
        time.sleep(3)
        # self.change_mode(teleop=True)
    
    # ======================== EXTRA ======================== #
    def change_mode(self, teleop):
        self.controllers["arm"]["left_arm"].change_mode(teleop)
        self.controllers["arm"]["right_arm"].change_mode(teleop)
        time.sleep(1)
    
    def set_map(self, map_path):
        self.controllers["mobile"]["slamware"].set_map(map_path)

if __name__ == "__main__":
    import time
    
    robot = XsparkRobot()
    # robot.set_up(teleop=True)

    robot.set_up(teleop=True)
    # robot.reset()
    time.sleep(3)
    debug_print("collect start!", "INFO")
    while True:
        data = robot.get()
        robot.collect(data)
        if is_enter_pressed():
            break
        else:
            time.sleep(1/30)
    
    robot.finish()
    robot.reset()
    robot.end_event.set()
    robot.controller_scheduler.stop()
    robot.sensor_scheduler.stop()
    # import pdb;pdb.set_trace()
    # robot.replay(data_path="save/test/0.hdf5",key_banned=["qpos"])
    # robot.show_pic(data_path="save/test/0.hdf5", pic_name="cam_left_wrist")
    # exit()